layout_spectrum: 1
typography_spectrum: 0.1096882
color:
  lightness: 0.606383
  brandStrength: 0.4212766
  saturation: 0.3106383
  rhythmicContrast: 0.1669174
  brandColors:
    - '#FFFFFF'
    - '#A1CD4D'
    - '#0293BE'
    - '#BDD888'
    - '#BDE8FC'
name: Matouka Consulting
